/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ultramarinos;
import java.io.File;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Paula
 */
public class AdministrarUsuarios extends javax.swing.JDialog {
    public Modelo model=new Modelo();
   
    
    public Object [][] datosUsuario;
    DefaultTableModel dataUser;
    private String usuario;
    /**
     * Creates new form AdministrarUsuarios
     */
    public AdministrarUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iniciarAyuda();
    }
    
    private void updateTablaUsuarios(){             
        String[] columNames = {"Nombre", "Usuario", "Contraseña"};  
     
        datosUsuario = model.getUsuarios();
        
        dataUser = new DefaultTableModel(datosUsuario,columNames);                        
        tablaUsuarios.setModel(dataUser); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric3 = new org.edisoncor.gui.label.LabelMetric();
        textNomUser = new org.edisoncor.gui.textField.TextField();
        textUsuario = new org.edisoncor.gui.textField.TextField();
        textContra = new org.edisoncor.gui.textField.TextField();
        botonRegUser = new org.edisoncor.gui.button.ButtonAction();
        botonEditUser = new org.edisoncor.gui.button.ButtonAction();
        botonElimUser = new org.edisoncor.gui.button.ButtonAction();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        botonAyuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoPantalla.jpg"))); // NOI18N

        labelMetric1.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric1.setText("Nombre");
        labelMetric1.setColorDeSombra(new java.awt.Color(153, 204, 0));
        labelMetric1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        labelMetric2.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric2.setText("Usuario");
        labelMetric2.setColorDeSombra(new java.awt.Color(153, 204, 0));
        labelMetric2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        labelMetric3.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric3.setText("Contraseña");
        labelMetric3.setColorDeSombra(new java.awt.Color(153, 204, 0));
        labelMetric3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        textNomUser.setForeground(new java.awt.Color(51, 51, 51));

        textUsuario.setForeground(new java.awt.Color(51, 51, 51));

        textContra.setForeground(new java.awt.Color(51, 51, 51));

        botonRegUser.setText("Registrar usuario");
        botonRegUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegUserActionPerformed(evt);
            }
        });

        botonEditUser.setText("Editar usuario");
        botonEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditUserActionPerformed(evt);
            }
        });

        botonElimUser.setText("Eliminar usuario");
        botonElimUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonElimUserActionPerformed(evt);
            }
        });

        tablaUsuarios.setBackground(new java.awt.Color(153, 204, 0));
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Usuario", "Contraseña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        botonAyuda.setText("Ayuda");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(botonRegUser, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(botonElimUser, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textContra, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAyuda)
                .addGap(26, 26, 26))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAyuda)
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMetric2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelMetric3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textContra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonElimUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 857, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void botonRegUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegUserActionPerformed
        // TODO add your handling code here:
        String nombre = textNomUser.getText();
        String usuario= textUsuario.getText();
        String contraseña = textContra.getText();
        model.insertarUsuario(nombre, usuario, contraseña);
        updateTablaUsuarios();
    }//GEN-LAST:event_botonRegUserActionPerformed

    private void botonEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditUserActionPerformed
        // TODO add your handling code here:
        String nombre = textNomUser.getText();
        String usuario= textUsuario.getText();
        String contraseña = textContra.getText();
        model.modificarUsuario(nombre, usuario, contraseña);
        updateTablaUsuarios();
    }//GEN-LAST:event_botonEditUserActionPerformed

    private void botonElimUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElimUserActionPerformed
        // TODO add your handling code here:
        String nombre= dataUser.getValueAt(tablaUsuarios.getSelectedRow(),0).toString();
        model.eliminarUsuario(nombre);
        updateTablaUsuarios();
    }//GEN-LAST:event_botonElimUserActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
        String nombre = dataUser.getValueAt(tablaUsuarios.getSelectedRow(),0).toString();
        String usuario= dataUser.getValueAt(tablaUsuarios.getSelectedRow(),1).toString();
        String contraseña= dataUser.getValueAt(tablaUsuarios.getSelectedRow(),2).toString();
        textNomUser.setText(nombre);
        textUsuario.setText(usuario);
        textContra.setText(contraseña);
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         updateTablaUsuarios();
    }//GEN-LAST:event_formWindowOpened

    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdministrarUsuarios dialog = new AdministrarUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAyuda;
    private org.edisoncor.gui.button.ButtonAction botonEditUser;
    private org.edisoncor.gui.button.ButtonAction botonElimUser;
    private org.edisoncor.gui.button.ButtonAction botonRegUser;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.label.LabelMetric labelMetric3;
    private org.edisoncor.gui.panel.Panel panel1;
    private javax.swing.JTable tablaUsuarios;
    private org.edisoncor.gui.textField.TextField textContra;
    private org.edisoncor.gui.textField.TextField textNomUser;
    private org.edisoncor.gui.textField.TextField textUsuario;
    // End of variables declaration//GEN-END:variables

 private void iniciarAyuda(){
        File archivo = new File("help/help.hs");
        URL hsURL;
        try{
            hsURL=archivo.toURI().toURL();
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker helpbroker = helpset.createHelpBroker();
            helpbroker.enableHelpOnButton(botonAyuda, "ventana_adminusuarios", helpset);
            helpbroker.enableHelpKey(getContentPane(), "ventana_adminusuarios", helpset);
           
            } catch (Exception ex) {
		Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
	
        }
    }
}
